cricket/api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
    ## User login details URL
    path('signup/',views.UserSignupAPIView.as_view(),name='signup'),
    path('login/',views.UserLoginAPIView.as_view(),name='login'),

    path('genrics/country_list/', views.CountryListAPIView.as_view(), name= 'country_list'),
    path('view/country_add/', views.CountryAddAPIView.as_view(), name= 'country_add'),

]

cricket/cricket/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('match/', include("match.urls", namespace='match')),
    path('api/', include("api.urls", namespace='api')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cricket/match/urls.py
from django.conf.urls import url
from . import views
# from .views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'match'
urlpatterns = [
##Profile urls
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.AdminProfileView.as_view(), name='profile'),
    path('change_password/', views.AdminChangePassword.as_view(), name='change-password'),

##masters urls
    path('countries/', views.CountryListView.as_view(), name='country-lists'),
    path('user_list/', views.UserListView.as_view(), name='user-lists'),
    path('add/', views.UserAddView.as_view(), name='user-add'),
    path('teams/', views.TeamListView.as_view(), name='team-lists'),
    path('players/<int:pk>/', views.PlayersView.as_view(), name='player-view'),
    path('team/<int:pk>/', views.PlayersListView.as_view(), name='player-lists'),

##Dashboard urls
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    # path('chart/', views.PieChartView.as_view(), name='chart-data'),

##Match urls
    path('match/view/', views.MatchView.as_view(), name='match_view'),
    path('match/add/', views.MatchAddView.as_view(), name='match-add'),
    path('match/ajax_team_list/', views.AjaxTeamListView.as_view(), name='team-list'),
    path('match/ajax_players_list/', views.AjaxPlayersListView.as_view(), name='player-list'),


##Scorecard urls
    path('score_view/', views.ScoreView.as_view(), name='score_view'),
    path('score_add/', views.ScoreAddView.as_view(), name='score_add'),
    path('score_player_view/', views.ScorePlayerView.as_view(), name='score_player_view'),
    path('team/score/<int:pk>/', views.TeamScoreView.as_view(), name='team-score'),

]

cricket/match/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.db.models import Sum,Count


# Create your models here.

"""
Model class: Base Modal class
Depdency: none
"""
class BaseModal(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    is_delete = models.BooleanField(default=False)

    class Meta:
        db_table = "BaseModal"

"""
Model class: Country class
Depdency: Base model
"""
class Country(models.Model):
    code = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=80, blank=False, unique=True)
    flag = models.ImageField(upload_to='country_flag/', blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "country"

"""
Model class: Team class
Depdency: Base model
"""
class Team(models.Model):
    name = models.CharField(max_length=80, unique=True)
    logo_uri = models.ImageField(upload_to='team_logo/', blank=False)
    club_state = models.CharField(max_length=80, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "team"

    @property
    def total_runs(self):
        runs_obj = ScoreCard.objects.filter(team=self.id)
        return runs_obj.aggregate(Sum('runs'))['runs__sum'] if runs_obj.exists() else 0
        # return total_runs

    @property
    def total_wickets(self):
        wickets_obj = ScoreCard.objects.filter(team=self.id)
        return wickets_obj.aggregate(Sum('wicket'))['wicket__sum'] if wickets_obj.exists() else 0

    @property
    def total_overs(self):
        overs_obj = ScoreCard.objects.filter(team=self.id)
        return overs_obj.aggregate(Sum('over'))['over__sum'] if overs_obj.exists() else 0

    @property
    def total_point(self):
        point_obj = ScoreCard.objects.filter(team=self.id)
        return point_obj.aggregate(Sum('point'))['point__sum'] if point_obj.exists() else 0

    @property
    def total_status(self):
        status_obj = ScoreCard.objects.filter(team=self.id)
        total_status = {}
        win=0; loss=0 ; draw=0
        for status in status_obj:
            if status.status == 'won':
                win=+1
            elif status.status == 'loss':
                loss=+1
            elif status.status == 'draw':
                draw=+1
            else:
                pass
        total_status["win"] = win ; total_status["loss"] = loss ; total_status["draw"] = draw
        return total_status

"""
Model class: User/Player abstracted class
Depdency: Base model, Country model
"""
class User(AbstractUser):

    USER_TYPE_CHOICE = (
        ('admin', 'Admin'),
        ('player', 'Player'),
    )

    PLAYER_TYPE_CHOICE = (
        ('batsman', 'Batsman'),
        ('bowler', 'Bowler'),
        ('wicket keeper', 'Wicket Keeper'),
        ('captain', 'Captain'),
        ('All rounder', 'All Rounder'),
    )

    email = models.EmailField(unique = True)
    image_uri = models.ImageField(upload_to='image_user/', blank=False)
    user_type = models.CharField(max_length=15, choices = USER_TYPE_CHOICE, default="player", blank=False)
    jersy_number = models.CharField(max_length=5, blank=False)
    country = models.ForeignKey(Country, null=True, blank=True, on_delete=models.CASCADE)
    team = models.ForeignKey(Team,related_name="player", null=True, blank=True, on_delete=models.CASCADE)
    player_type = models.CharField(max_length=20, choices = PLAYER_TYPE_CHOICE, default="all rounder", blank=False)
    random_string = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.email

    class Meta:
        db_table = "user"

    def playertype(self):
        return str(self.first_name)+" "+str(self.last_name)+" - "+str(self.player_type)

    @property
    def total_runs(self):
        runs_obj = ScoreCardPlayer.objects.filter(player_id=self.id)
        return runs_obj.aggregate(Sum('runs'))['runs__sum'] if runs_obj.exists() else 0

    @property
    def total_wickets(self):
        wickets_obj = ScoreCardPlayer.objects.filter(player_id=self.id)
        return wickets_obj.aggregate(Sum('wicket'))['wicket__sum'] if wickets_obj.exists() else 0

    @property
    def total_overs(self):
        overs_obj = ScoreCardPlayer.objects.filter(player_id=self.id)
        return overs_obj.aggregate(Sum('over'))['over__sum'] if overs_obj.exists() else 0

    @property
    def total_meadan_overs(self):
        meadan_overs_obj = ScoreCardPlayer.objects.filter(player_id=self.id)
        return meadan_overs_obj.aggregate(Sum('meadan_over'))['meadan_over__sum'] if meadan_overs_obj.exists() else 0

    @property
    def total_fours(self):
        fours_obj = ScoreCardPlayer.objects.filter(player_id=self.id)
        return fours_obj.aggregate(Sum('fours'))['fours__sum'] if fours_obj.exists() else 0

    @property
    def total_sixs(self):
        sixs_obj = ScoreCardPlayer.objects.filter(player_id=self.id)
        return sixs_obj.aggregate(Sum('sixs'))['sixs__sum'] if sixs_obj.exists() else 0

    @property
    def total_fifty(self):
        return ScoreCardPlayer.objects.filter(player_id=self.id).aggregate(Sum('fifty'))['fifty__sum']

    @property
    def total_hundred(self):
        return ScoreCardPlayer.objects.filter(player_id=self.id).aggregate(Sum('hundred'))['hundred__sum']

    @property
    def total_man_of_match(self):
        return ScoreCardPlayer.objects.filter(player_id=self.id,man_of_match=True).count


"""
Model class: Match details class
Depdency: Base model, Team model
"""
class DeviceDetail(BaseModal):
    PLATFORM_CHOICE = (
        ('android', 'android'),
        ('ios', 'ios'),
        ('unknown', 'unknown')
    )
    user = models.ForeignKey(User, related_name= "user_device_detail", on_delete= models.CASCADE)
    platform = models.CharField(max_length= 30, choices= PLATFORM_CHOICE, default= "unknown")
    device_id = models.CharField(max_length= 200, null= False, blank= False, unique= True)
    device_token = models.TextField(null= True, blank= True)
    app_version = models.CharField(max_length= 100, null= True, blank= True)
    access_token = models.TextField(null= True, blank= True)
    refresh_token = models.TextField(null= True, blank= True)

    def __str__(self):
        return self.platform

    def is_ios(self):
        return True if self.platform in ["ios"] else False

    def is_android(self):
        return True if self.platform in ["android"] else False

    class Meta:
        db_table = "device_detail"



"""
Model class: Match details class
Depdency: Base model, Team model
"""
class Match(models.Model):
    name = models.CharField(max_length = 100, blank=False)
    team1 = models.ForeignKey(Team, related_name="team1", blank=False, on_delete=models.CASCADE)
    team2 = models.ForeignKey(Team, related_name="team2", blank=False, on_delete=models.CASCADE)
    match_date = models.DateTimeField(null=True, blank=True)
    match_result = models.CharField(max_length=100, null=True, blank= True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "match"


"""
Model class: Match Player details class
Depdency: Base model, User model, Team modal
"""
class MatchPlayerDetails(BaseModal):
    match_id = models.ForeignKey(Match, related_name="match_player", blank=False, on_delete=models.CASCADE)
    team_id = models.ForeignKey(Team, related_name="match_team", blank=False, on_delete=models.CASCADE)
    player = models.ForeignKey(User, related_name="user_player", blank=False, on_delete=models.CASCADE)

    def __str__(self):
        return self.match_id.name

    class Meta:
        db_table = "match_player_detail"


"""
Model class: ScoreCard class
Depdency: Base model, User model, Team modal
"""
class ScoreCard(BaseModal):
    SCORE_STATUS_CHOICE = (
        ('won', 'Won'),
        ('loss', 'Loss'),
        ('draw', 'Draw'),
    )

    match = models.ForeignKey(Match, related_name="score_card_match", blank=False, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, related_name="score_card_team", blank=False, on_delete=models.CASCADE)
    runs = models.IntegerField(blank=False, default=0)
    wicket = models.IntegerField(blank=False, default=0)
    over = models.FloatField(blank=False, default=0.0)
    status = models.CharField(max_length=10, choices = SCORE_STATUS_CHOICE, blank=True)
    point = models.IntegerField(blank=False, default=0)

    def __str__(self):
        return self.match.name

    class Meta:
        db_table = "score_card"

    def score_status_list(self):
        return self.status


"""
Model class: ScoreCardPlayer class
Depdency: Base model, User model, Team modal
"""
class ScoreCardPlayer(BaseModal):
    PLAYER_STATUS_CHOICE = (
        ('out', 'Out'),
        ('notout', 'Not Out'),
        ('notplayed', 'Not Played'),
    )

    score = models.ForeignKey(ScoreCard, related_name="score_player", blank=False, on_delete=models.CASCADE)
    player_id = models.ForeignKey(User, related_name="player_score", blank=False, on_delete=models.CASCADE)
    runs = models.IntegerField(blank=False, default=0)
    wicket = models.IntegerField(blank=False, default=0)
    over = models.FloatField(blank=False, default=0.0)
    fifty = models.IntegerField(blank=False, default=0)
    hundred = models.IntegerField(blank=False, default=0)
    meadan_over = models.FloatField(blank=False, default=0)
    fours = models.IntegerField(blank=False, default=0)
    sixs = models.IntegerField(blank=False, default=0)
    man_of_match = models.BooleanField(blank=False, default=False)
    status = models.CharField(max_length=10, choices = PLAYER_STATUS_CHOICE, blank=True)

    def __str__(self):
        return self.player_id.first_name

    class Meta:
        db_table = "score_card_player"

cricket/templates/base_site.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        {% block meta %}
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
            <meta name="description" content="">
            <meta name="author" content="">
        {% endblock meta %}

        <title>Cricket Demo: {% block title %}{% endblock %}</title>

        {% block stylesheets %}

            <!-- Bootstrap Core CSS -->
            <link rel="stylesheet" href="{% static 'assets//plugins/bootstrap/css/bootstrap.min.css'%}">

            <!-- Font CSS -->
            <link rel="stylesheet" href="{% static 'css/all_icons.css'%}">

            <!-- MetisMenu CSS -->
            <link rel="stylesheet" href="{% static 'assets/plugins/metisMenu/metisMenu.min.css'%}">

            <!-- Loader CSS -->
            <link rel="stylesheet" href="{% static 'css/loader.css'%}">
            <link rel="stylesheet" href="{% static 'css/custom.css'%}">

            <!-- Custom CSS -->
            <link rel="stylesheet" href="{% static 'css/pazi.min.css'%}">

            <!-- Change Color CSS -->
            <link rel="stylesheet" href="{% static 'css/skin/default-skin.css'%}" />

            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

            <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
            <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
            <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		    <![endif]-->
        {% endblock stylesheets %}

    {% endblock head %}
</head>

<body>
{% block body %}
     <div id="wrapper">
        <div class="fakeLoader"></div>

            {% block sidebar %}
         <nav class="navbar navbar-default navbar-static-top" style="margin-bottom: 0">
            {% include "sidebar.html" %}
         </nav>
            {% endblock sidebar %}

            {% block content %}
                <!-- {{ content }} -->
            {% endblock content %}

            {% block footer %}
                <footer>
                    {% include "footer.html" %}
                </footer>
            {% endblock footer %}
        </div>


    {% block javascripts %}
        <!-- jQuery -->
    <!--<script src="{% static 'assets/plugins/jquery/dist/jquery.min.js' %}"></script>-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- ChartJS -->
    <script src="{% static 'assets/plugins/chart.js/Chart.js' %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'assets/plugins/metisMenu/metisMenu.min.js' %}"></script>

    <!-- Loader JavaScript -->
    <script src="{% static 'js/loader.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/pazi.min.js' %}"></script>

    <!-- Custom Float JavaScript -->
    <script src="{% static 'js/custom/dashboard/dashboard1.js' %}"></script>
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>

    <script>
      $(document).ready(function(){
         $.ajax({
          url: $("#container").attr("data-url"),
          dataType: 'json',
          success: function (data) {
            Highcharts.chart("container", data);
          }
        });
    });
    $(document).ready(function(){
    $(".highcharts-credits").hide();

});

    </script>
    <script>

        $("#update-show").click(function() {
            $("#update-profile").removeClass("hidden");
        });
        $("#update-hide").click(function() {
            $("#update-profile").addClass("hidden");
        });

    </script>
    <script>

$("#ChangePassword").validate({
rules: {
    oldpassword: {
    required: true,
    },
    newpassword: {
    required: true,
    minlength: 5,
    },
    confirmpassword: {
    required: true,
    minlength: 5,
    equalTo : "#password",
    },


    }
    });
</script>
<script>

$("#Adminid").validate({
rules: {
    name: {
    required: true,
    },
    email: {
    required: true,
    },
    phone_no: {
    required: true,
    digits:true
    }


    }
    });
</script>
<script>
jQuery.validator.addMethod("Fname", function(value, element) {
return value.match(/[a-zA-Z]/);
},"Please enter characters only");
jQuery.validator.addMethod("Lname", function(value, element) {
return value.match(/[a-zA-Z]/);
},"Please enter characters only");
jQuery.validator.addMethod("Email", function(value, element) {
return value.match(/[a-zA-Z]/);
},"Please enter characters only");

$("#user").validate({
rules: {

    first_name: {
    required: true,
    Fname:true,
    },
    last_name: {
    required: true,
    Lname:true,
    },

    email: {
    required: true,
    Email:true,
    },
    jersy: {
    required: true,
    number:true,
    },
    country: {
    required: true,
    },
    team: {
    required: true,
    },
     image: {
    required: true,
    },
    player: {
    required: true,
    },
    },
    messages: {

first_name:{
required:"Please Enter Your First Name",
Fname:"Please Enter Alphanumeric Only",
},
last_name:{
required:"Please Enter Your Last Name",
Lname:"Please Enter Alphanumeric Only",
},
email:{
required:"Please Enter Your Email",
Email:"Please Enter Alphanumeric Only",
},
country: {
required:"Select Your Country",
},

team:{
required:"Select Your Team",
},
image:{
required:"Choose Your Images",
},
jersy:{
required:"Please Enter Your Jersy No.",
},
player:{
required:"Please Enter Your Jersy No.",
},

    }
    });
</script>
<script>

$("#match").validate({
rules: {
    match: {
    required: true,
    },
    team1: {
    required: true,
    },
    players1: {
    required: true,
    },
    team2: {
    required: true,
    },
    players2: {
    required: true,
    },

    },
   messages: {


team1: {
required:"Select Your First Team",
},

players1:{
required:"Select Your Players",
},
match:{
required:"Enter Your Match",
},
team2:{
required:"Select the Second Team",
},
players2:{
required:"Select the Players",
},


    }
    });
</script>
<script>
$("#score").validate({
        rules: {
    match: {
    required: true,
    },
    team: {
    required: true,
    },
    runs: {
    required: true,
    digits:true,
    },
    wicket: {
    required: true,
    digits:true,
    },
    over: {
    required: true,
    number: true,
    },
    status: {
    required: true,
    },
    point: {
    required: true,
    digits:true,
    },
    },
    messages: {


team: {
required:"Select Your Team",
},
status:{
required:"Select Your Status",
},
match:{
required:"Select Your Match",
},
runs:{
required:"Enter The Runs",
},
wicket:{
required:"Enter The Wickets",
},
over:{
required:"Enter The Overs",
},
point:{
required:"Enter The Points",
},

    }
    });
</script>
<script>
$('#mySelect1').on('change', function(){

var id = $(this).val();
var csrfmiddlewaretoken = $('input[name=csrfmiddlewaretoken]').val();
    if(id!=''){
         $.ajax({
            type: 'POST',
            url:  '/match/match/ajax_team_list/',
            data:  {'id': id,'csrfmiddlewaretoken': csrfmiddlewaretoken},
            success: function (response) {
                let dropdown = document.getElementById('mySelect2');
                let dropdown1 = document.getElementById('players1');
                dropdown.length = 0;
                dropdown1.length = 0;
                let defaultOption = document.createElement('option');
                let defaultOption1 = document.createElement('option');
                defaultOption.text = 'Select Team';
                defaultOption1.text = 'Select Players';
                defaultOption.value = "";
                defaultOption1.value = "";
                dropdown.add(defaultOption);
                dropdown1.add(defaultOption1);
                dropdown.selectedIndex = 0;
                dropdown1.selectedIndex = 0;

                if(response.status == 'success'){

                    var obj = response.result;
                    let option;
                    for (let i = 0; i < obj.length; i++) {
                      option = document.createElement('option');
                      option.text = obj[i].name;
                      option.value = obj[i].id;
                      dropdown.add(option);
                    }


                var obj1 = response.result1;
                    let option1;
                    for (let i = 0; i < obj1.length; i++) {
                      option1 = document.createElement('option');
                      option1.text = obj1[i].name;
                      option1.value = obj1[i].id;
                      dropdown1.add(option1);
                    }


                } else if(response.status == 'error') {

                   } else {
                    return false;
                }

            }
        });

    } else {

     return false;
    }

});
</script>

<script>
$('#mySelect2').on('change', function(){

var id = $(this).val();
var csrfmiddlewaretoken = $('input[name=csrfmiddlewaretoken]').val();
    if(id!=''){
         $.ajax({
            type: 'POST',
            url:  '/match/match/ajax_players_list/',
            data:  {'id': id,'csrfmiddlewaretoken': csrfmiddlewaretoken},
            success: function (response) {
                let dropdown = document.getElementById('players2');
                dropdown.length = 0;
                let defaultOption = document.createElement('option');
                defaultOption.text = 'Select Players';
                defaultOption.value = "";
                dropdown.add(defaultOption);
                dropdown.selectedIndex = 0;

                if(response.status == 'success'){

                    var obj = response.result;
                    let option;
                    for (let i = 0; i < obj.length; i++) {
                      option = document.createElement('option');
                      option.text = obj[i].name;
                      option.value = obj[i].id;
                      dropdown.add(option);
                    }

                } else if(response.status == 'error') {

                   } else {
                    return false;
                }

            }
        });

    } else {

     return false;
    }

});
</script>

    {% endblock %}
{% endblock body %}
</body>
</html>

cricket/templates/footer.html
<div class="container-fluid text-right">
    © 2019 Admin of cricketdemo.com
</div>

cricket/templates/paginator.html
{% load common_tags %}
<ul class="pagination">
    {% if paginator.has_previous %}
    <li><a href="?{% url_replace request 'page' paginator.previous_page_number %}">&laquo;</a></li>
    {% else %}
    <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.paginator.page_range %}
    {% if paginator.number == i %}
    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
    <li><a href="?{% url_replace request 'page' i %}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}
    {% if paginator.has_next %}
    <li><a href="?{% url_replace request 'page' paginator.next_page_number %}">&raquo;</a></li>
    {% else %}
    <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
</ul>

cricket/templates/sidebar.html
{% load static %}
{% get_static_prefix as STATIC %}

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
                <a class="navbar-brand" href="{% url 'match:dashboard' %}" style="padding: 0;"><img src="{{STATIC}}assets/img/cri-logo.png" class="img-responsive" alt="Logo"></a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-left header-search-form hidden-xs">
                <li><a class="menu-brand" id="menu-toggle"><span class="fa-2x fa fa-bars"></span></a></li>
            </ul>
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        {% if request.user.image_uri %}
                        <img src="/media_cdn/{{request.user.image_uri}}" height="30" width="30"><span>{{request.user.username}}</span>
                        {% else %}
                        <img src="/static/assets/img/default-profile.png" alt="Default"  height="30" width="30">
                        {% endif %}
						</a>
                    <ul class="dropdown-menu dropdown-user right-swip">
                        <li><a href="{% url 'match:profile' %}"><i class="fa fa-user fa-fw"></i> Profile</a>
                        </li>
                        <li><a href="{% url 'match:change-password' %}"><i class="fa fa-gear fa-fw"></i> Change Password</a>
                        </li>
                        <li><a href="{% url 'match:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>

                    </ul>
                    <!-- /.dropdown-user -->
                </li>
            </ul>
            <!-- /.navbar-top-links -->

            <!-- Sidebar Navigation -->
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="{% if nbar == 'dashboard' %}active{% endif %}">
                            <a href="{% url 'match:dashboard' %}"><i class="fa fa-dashboard"></i>Dashboard</a>
                        </li>
                        <li class="{% if nbar == 'user-lists' %}active{% endif %}">
                            <a href="{% url 'match:user-lists' %}"><i class="fa fa-users"></i>Player</a>
                        </li>
                        <li class="{% if nbar == 'teams' %}active{% endif %}">
                            <a href="{% url 'match:team-lists' %}"><i class="fa fa-futbol-o"></i>Team</a>
                        </li>
                        <li class="{% if nbar == 'match_list' %}active{% endif %}">
                            <a href="{% url 'match:match_view' %}"><i class="fa fa-bullseye "></i>Matches</a>
                        </li>
                        <li class="{% if nbar == 'score_list' %}active{% endif %}">
                            <a href="{% url 'match:score_view' %}"><i class="fa  fa-pied-piper-alt"></i>ScoreCard</a>
                        </li>
                        <li class="{% if nbar == 'countries' %}active{% endif %}">
                            <a href="{% url 'match:country-lists' %}"><i class="fa fa-flag"></i>Country</a>
                        </li>
                        <!---->
                        <li>
                            <a href="{% url 'match:logout' %}"><i class="fa fa-sign-out"></i>Logout</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>