cricket/api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
    ## User login details URL
    path('signup/',views.UserSignupAPIView.as_view(),name='signup'),
    path('login/',views.UserLoginAPIView.as_view(),name='login'),

    path('genrics/country_list/', views.CountryListAPIView.as_view(), name= 'country_list'),
    path('view/country_add/', views.CountryAddAPIView.as_view(), name= 'country_add'),

]

cricket/cricket/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('match/', include("match.urls", namespace='match')),
    path('api/', include("api.urls", namespace='api')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cricket/match/urls.py
from django.conf.urls import url
from . import views
# from .views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'match'
urlpatterns = [
##Profile urls
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.AdminProfileView.as_view(), name='profile'),
    path('change_password/', views.AdminChangePassword.as_view(), name='change-password'),

##masters urls
    path('countries/', views.CountryListView.as_view(), name='country-lists'),
    path('user_list/', views.UserListView.as_view(), name='user-lists'),
    path('add/', views.UserAddView.as_view(), name='user-add'),
    path('teams/', views.TeamListView.as_view(), name='team-lists'),
    path('players/<int:pk>/', views.PlayersView.as_view(), name='player-view'),
    path('team/<int:pk>/', views.PlayersListView.as_view(), name='player-lists'),

##Dashboard urls
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    # path('chart/', views.PieChartView.as_view(), name='chart-data'),

##Match urls
    path('match/view/', views.MatchView.as_view(), name='match_view'),
    path('match/add/', views.MatchAddView.as_view(), name='match-add'),
    path('match/ajax_team_list/', views.AjaxTeamListView.as_view(), name='team-list'),
    path('match/ajax_players_list/', views.AjaxPlayersListView.as_view(), name='player-list'),


##Scorecard urls
    path('score_view/', views.ScoreView.as_view(), name='score_view'),
    path('score_add/', views.ScoreAddView.as_view(), name='score_add'),
    path('score_player_view/', views.ScorePlayerView.as_view(), name='score_player_view'),
    path('team/score/<int:pk>/', views.TeamScoreView.as_view(), name='team-score'),

]

cricket/match/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from match.models import User, Country, Team, Match, ScoreCard, ScoreCardPlayer,MatchPlayerDetails
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.shortcuts import HttpResponseRedirect,redirect
from django.urls import reverse_lazy,reverse
from util.utility import generate_random_string,send_password_email,paginator_class
from django.db.models import Q,Max
from match.serializers import TeamListSerializer,PlayerListSerializer
from django.http import JsonResponse
# Create your views here.

## Login for user and player
class LoginView(View):

    def get(self,request):
        try:
            msg = request.session["msg"]
            del request.session["msg"]
        except:
            msg = ''
        return render(request,'common/login.html',{"msg": msg})

    def post(self,request):
        data = request.POST
        username = data.get('username')
        password = data.get('password')
        user = authenticate(username = username,password = password)

        if user:
            group_name = user.groups.filter(name = "admin")

        if user is not None and group_name.exists():
            login(request, user)
            if not data.get('options'):
                request.session.set_expiry(0)

            return redirect("match:dashboard")
        else:
            msg = "Username or Password is wrong"
            request.session["msg"] = msg
            return redirect("match:login")


## Logout for user and player
class LogoutView(View):

    def get(self,request):
        logout(request)
        return redirect("match:login")

class AdminProfileView(LoginRequiredMixin, View):

    def get(self, request):
        return render(request, "common/profile.html")

    def post(self, request):
        full_name = request.POST.get("name")
        if " " in full_name:
            first_name, last_name = full_name.split(" ", 1)
        else:
            first_name = full_name
            last_name = ''

        user = request.user
        user.image_uri = request.FILES.get("image", user.image_uri)
        user.email = request.POST.get("email", user.email)
        user.first_name = first_name
        user.last_name = last_name
        user.save()
        return redirect("match:profile")

#### Functionility not working
class AdminChangePassword(LoginRequiredMixin, View):

    def get(self,request):
        try:
            msg = request.session["msg"]
            del request.session["msg"]
        except:
            msg = ''

        return render(request,"common/change_password.html",{"msg": msg})



class UserListView(LoginRequiredMixin, View):

    def get(self,request):
        try:
            message = request.session["message"]
            is_message = request.session["is_message"]
            del request.session["message"]
            del request.session["is_message"]
        except:
            message = ''
            is_message =''

        query = request.GET.get('search')

        if query is not None:
            lookups = Q(first_name__icontains=query) | Q(username__icontains=query)| Q(email__icontains=query)|Q(last_name__icontains = query)
            user_list = User.objects.filter(lookups).exclude(groups__name='admin')
        else:
            user_list = User.objects.all().exclude(groups__name='admin')

        page = request.GET.get('page',1)
        records_per_page = 10
        user_list = paginator_class(user_list,page,records_per_page)

        context = {
            'users_list': user_list,
            "nbar": "user-lists",
            "message": message,
            "is_message": is_message
        }

        return render(request,'user_managements/usermanagement.html',context)


##Dashboard view
class DashboardView(LoginRequiredMixin,View):

    login_url='match/login/'

    def get(self,request):
        scorecard_obj = ScoreCard.objects.all()
        Max_runs_obj = scorecard_obj.order_by('-runs')
        Max_wicket_obj = scorecard_obj.order_by('-wicket')
        max_win_obj = ScoreCard.objects.filter(status="won").order_by('-status')
        max_win_count=max_win_obj.count()

        context={
            "Max_runs_obj":Max_runs_obj,
            "Max_wicket_obj":Max_wicket_obj,
            "max_win_obj":max_win_obj,
            "max_win_count":max_win_count
        }

        return render(request, "user_managements/dashboard.html",context)


## Player add functionaility
class UserAddView(LoginRequiredMixin,View):

    def get(self,request,*args, **kwargs):
        try:
            message = request.session["message"]
            is_message = request.session["is_message"]
            del request.session["message"]
            del request.session["is_message"]
        except:
            message = ''
            is_message =''
        # user_group = self.request.user.groups.filter(name='admin').exists()
        # if user_group:

        countries = Country.objects.all()
        teams = Team.objects.all()
        context = {
            "title": "User Add",
            "url": reverse_lazy('match:user-add'),
            "countries": countries,
            "teams": teams,
            "message":message,
            "is_message":is_message
        }

        return render(self.request, 'user_managements/user_add.html', context)


    def post(self,request, *args, **kwargs):
        data = self.request.POST
        email = data.get("email")
        profile_img = self.request.FILES.get("image")
        first_name = data.get("first_name")
        last_name = data.get("last_name")
        jersy_number = data.get("jersy")
        country = Country.objects.get(id=data.get("country"))
        team = Team.objects.get(id=data.get("team"))
        player_type = data.get("player")
        password = email[:4]+generate_random_string(4)
        try:
            user = User.objects.create_user(username=email,password=password)
            send_password_email(email,password)
            user.email = email
            user.first_name = first_name
            user.last_name = last_name
            user.jersy_number = jersy_number
            user.country = country
            user.team = team
            user.player_type = player_type
            user.random_string = password
            user.save()
            message ="Added  successfully."
            is_message =1
            request.session["is_message"] = is_message
            request.session["message"] = message
        except:
            message = "Email already exist"
            is_message = 0
            request.session["is_message"] = is_message
            request.session["message"] = message
            return redirect("match:user-add")

        return redirect("match:user-lists")


##Country listing
class CountryListView(LoginRequiredMixin,View):

    def get(self,request,*args,**kwargs):
        try:
            message = request.session["message"]
            is_message = request.session["is_message"]
            del request.session["message"]
            del request.session["is_message"]
        except:
            message = ''
            is_message = ''

        query = request.GET.get('search')

        if query is not None:
            lookups = Q(code__icontains=query) | Q(name__icontains=query)
            countries = Country.objects.filter(lookups)
        else:
            countries = Country.objects.all()

        page = request.GET.get('page', 1)
        records_per_page = 10
        countries = paginator_class(countries, page, records_per_page)

        context = {
            'countries': countries,
            "nbar": "countries",
            "message": message,
            "is_message": is_message
        }

        return render(request, 'countries/countries.html', context)


##Team listing
class TeamListView(LoginRequiredMixin,View):

    def get(self,request,*args,**kwargs):
        try:
            message = request.session["message"]
            is_message = request.session["is_message"]
            del request.session["message"]
            del request.session["is_message"]
        except:
            message = ''
            is_message = ''

        query = request.GET.get('search')

        if query is not None:
            lookups = Q(code__icontains=query) | Q(name__icontains=query)
            teams = Team.objects.filter(lookups)
        else:
            teams = Team.objects.all()

        page = request.GET.get('page', 1)
        records_per_page = 10
        teams = paginator_class(teams, page, records_per_page)

        context = {
            'teams': teams,
            "nbar": "teams",
            "message": message,
            "is_message": is_message
        }

        return render(request, 'team/team.html', context)


##Match view logic
class MatchView(LoginRequiredMixin, View):

    def get(self,request):
        try:
            message = request.session["message"]
            is_message = request.session["is_message"]
            del request.session["message"]
            del request.session["is_message"]
        except:
            message = ''
            is_message =''
        query = request.GET.get('search')

        if query is not None:
            lookups = Q(name__icontains=query) | Q(match_result__icontains=query)
            match_list = Match.objects.filter(lookups)
        else:
            match_list = Match.objects.all()

        page = request.GET.get('page',1)
        records_per_page = 10
        match_list = paginator_class(match_list, page, records_per_page)

        context = {
            'match_list': match_list,
            "nbar": "user-lists",
            "message": message,
            "is_message": is_message
        }

        return render(request,'match/matchview.html',context)



##Score view logic
class ScoreView(LoginRequiredMixin, View):

    def get(self,request):
        try:

cricket/match/templates/team/player_detail.html
{% extends "base_site.html" %}
{% block content %}
    {% block title %} Incident Reporting {% endblock title %}
    <!-- {{ content }} -->
<style>
.panel-body img {
  border-radius: 100%;
  margin: 20px auto;
}
</style>

    <div id="page-wrapper" style="margin-top: 32px;">
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-themecolor">Player Information</h3>
                </div>

            </div>
            <div class="clearfix"></div>

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-header">
                            <h2>{{ title }}</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="card-body">


                            <div class="panel-body">
                                {% if user_obj %}
                                <div class="col-md-4 text-center col-lg-3">
                                    {% if user_obj.image_uri %}
                                        <img src="/media_cdn/{{user_obj.image_uri}}"  alt="Avatar" class="center" height="150" width="150">
                                    {% else %}
                                        <img src="/static/assets/img/default-profile.png" alt="Default"  height="100" width="100">
                                    {% endif %}
                                </div>


                                <div class=" col-md-8 col-lg-8">
                                    <table class="table table-user-information">
                                        <tbody>
                                        <tr>
                                            <td>Country:</td>
                                            <td>{{ user_obj.country.name }}</td>
                                        </tr>
                                        <tr>
                                            <td>Team:</td>
                                            <td>{{ user_obj.team.name  }}</td>
                                        </tr>
                                        <tr>
                                            <td>Name:</td>
                                            <td>{{ user_obj.get_full_name }}</td>
                                        </tr>
                                        <tr>
                                            <td>Email Id:</td>
                                            <td>{{ user_obj.email }}</td>
                                        </tr>
                                        <tr>
                                            <td>Player Type:</td>
                                            <td>{{ user_obj.player_type }}</td>
                                        </tr>
                                        <tr>
                                            <td>Jersy Number:</td>
                                            <td>{{ user_obj.jersy_number }}</td>
                                        </tr>
                                        <tr>
                                            <td>Runs:</td>
                                            <td>{{user_obj.total_runs }}</td>
                                        </tr>
                                        <tr>
                                            <td>Total Wickets:</td>
                                            <td>{{ user_obj.total_wickets }}</td>
                                        </tr>
                                        <tr>
                                            <td>Total Overs:</td>
                                            <td>{{ user_obj.total_overs }}</td>
                                        </tr>
                                        <tr>
                                            <td>Total Maiden Over:</td>
                                            <td>{{ user_obj.total_meadan_overs }}</td>
                                        </tr>
                                        <tr>
                                            <td>Total Four:</td>
                                            <td>{{ user_obj.total_fours }}</td>
                                        </tr>
                                        <tr>
                                            <td>Total Six:</td>
                                            <td>{{ user_obj.total_sixs }}</td>
                                        </tr>
                                        <tr>
                                            <td>Total Fifty:</td>
                                            <td>{{ user_obj.total_fifty }}</td>
                                        </tr>
                                        <tr>
                                            <td>Total Hundred:</td>
                                            <td>{{ user_obj.total_hundred }}</td>
                                        </tr>
                                        <tr>
                                            <td>Total Man of Match:</td>
                                            <td>{{ user_obj.total_man_of_match }}</td>
                                        </tr>

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            {% else %}
                                <p>No Player Information</p>
                                {% endif %}
                        </div>

                    </div>
                </div>
            </div>
            </div>

        </div>
{% endblock content %}

cricket/match/templates/team/team.html
{% extends "base_site.html" %}
{% block title %} Profile {% endblock title %}
{% block content %}
<div id="page-wrapper">
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-themecolor">Team</h3>
                </div>
                <div class="col-md-7 align-self-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'match:dashboard' %}">Home</a></li>
                        <li class="breadcrumb-item active">Team</li>
                    </ol>
                </div>
            </div>
            <div class="container-fluid">
                <!-- row -->
                <div class="row">
                    {% for team in teams %}
                        <div class="col-sm-6 col-sm-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <div class="table-wrapper">
                                        <div class="row">
                                            <div class="col-lg-12 col-md-12">
                                                <div class="card box-primary">
                                                    <div class="card-body">

                                                        <br>
                                                        <div class="row">
                                                            <div class="col-md-4">
                                                                {% if request.user.image_uri %}
                                                                <img class="profile-user-img img-responsive img-circle" src="/media_cdn/{{team.logo_uri}}" alt="profile picture">
                                                                {% else %}
                                                                <img class="profile-user-img img-responsive img-circle" src="/media_cdn/profile/default.png" alt="Default"  height="70" width="70">
                                                                {% endif %}
                                                            </div>
                                                            <div class="col-md-8">
                                                                <h3 class="profile-username"><span class = "fa fa-user">   </span> {{team.name}}</h3>
                                                                <p> Club Name:  {{team.club_state}}</p>
                                                                <p> Total Runs: {{team.total_runs}}</p>
                                                                <p> Total Wickets:  {{team.total_wickets}}</p>
                                                                <p> Total Wins:  {{team.total_status.win}}</p>
                                                                <p> Total Loss:  {{team.total_status.loss}}</p>
                                                                <p> Total Draw:  {{team.total_status.draw}}</p>
                                                            </div>
                                                        </div>
                                                        <br>
                                                        <p class="clearfix"><a href="{% url 'match:player-lists' team.id%}" target="_blank" class="btn btn-success">&nbsp;List of Player</a></p>
                                                    </div>
                                                    <!-- /.box-body -->
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- ./Basic Table -->
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
    {% endblock content %}

cricket/match/templates/team/team_player_list.html
{% extends "base_site.html" %}
{% block title %} User Management {% endblock title %}
{% block content %}
<div id="page-wrapper">
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-themecolor">Player Management</h3>
                </div>
                <div class="col-md-7 align-self-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'match:team-lists' %}">Team</a></li>
                        <li class="breadcrumb-item active">Player List</li>
                    </ol>
                </div>
            </div>
            <div class="container-fluid">
                    <div style="text-align: center;">
                                {% if is_message == 1 %}
                                    <div class="alert alert-success">
                                    {{message}}
                                    </div>
                                {% else %}

                                {% endif %}

                                </div>
                <!-- row -->
                <div class="x_panel">
                        <div class="x_title">
                            <h2>Search</h2>
                            <div class="clearfix"></div>
                            <div class="row">
                                <div class="col-sm-6 col-md-4">
                                 <form method="get">
                                     <div class="x_content">
                                         <div class="input-group">
                                             <input type="text" class="form-control" name="search">
                                             <span class="input-group-btn">
                                                 <input class="btn btn-success add-category-btn" type="submit" value="Search">
                                             </span>
                                         </div>
                                     </div>
                                 </form>
                            </div>





                        </div>
                    </div>
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <div class="table-wrapper">
                                        <div class="table-responsive text-nowrap">
                                            <table class="table table-striped table-hover table-sm">
                                                <thead>
                                                    <tr>
                                                        <th><b>S.No.</b></th>
                                                        <th><b>Profile Pic</b></th>
                                                        <th><b>First Name</b></th>
                                                        <th><b>Last Name</b></th>
                                                        <th><b>Player Type</b></th>
                                                        <th><b>Email ID</b></th>
                                                        <th><b>View</b></th>

                                                    </tr>
                                                </thead>
                                                <tbody>
                                                {% for player in player_obj %}
                                                    <tr>
                                                        <td>{{ forloop.counter }}</td>
                                                        <td>
                                                            {% if player.image_uri %}
                                                            <img src="/media_cdn/{{user.image_uri}}"  alt="Avatar" height="50" width="50">
                                                            {% else %}
                                                            <img src="/static/assets/img/default-profile.png" alt="Default"  height="50" width="50">
                                                            {% endif %}

                                                        </td>
                                                        <td>{{ player.first_name }}</td>
                                                        <td>{{ player.last_name }}</td>
                                                        <td>{{ player.player_type }}</td>
                                                        <td>{{ player.email }}</td>
                                                        <td><a href="{% url 'match:player-view' player.id%}">
                                                            <span class="fa fa-eye fa-lg blue"></span></td>
                                                    </tr>
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="row">
                                    <div class="col-md-12">
                                        {% include 'paginator.html' with paginator=player_obj %}
                                    </div>
                                    </div>
                                </div>
                                    </div>
                                </div>
                            </div>
                            <!-- ./Basic Table -->
                        </div>
                    </div>
                </div>
            </div>


    {% endblock content %}