cricket/api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
    ## User login details URL
    path('signup/',views.UserSignupAPIView.as_view(),name='signup'),
    path('login/',views.UserLoginAPIView.as_view(),name='login'),

    path('genrics/country_list/', views.CountryListAPIView.as_view(), name= 'country_list'),
    path('view/country_add/', views.CountryAddAPIView.as_view(), name= 'country_add'),

]

cricket/cricket/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('match/', include("match.urls", namespace='match')),
    path('api/', include("api.urls", namespace='api')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cricket/match/urls.py
from django.conf.urls import url
from . import views
# from .views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'match'
urlpatterns = [
##Profile urls
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.AdminProfileView.as_view(), name='profile'),
    path('change_password/', views.AdminChangePassword.as_view(), name='change-password'),

##masters urls
    path('countries/', views.CountryListView.as_view(), name='country-lists'),
    path('user_list/', views.UserListView.as_view(), name='user-lists'),
    path('add/', views.UserAddView.as_view(), name='user-add'),
    path('teams/', views.TeamListView.as_view(), name='team-lists'),
    path('players/<int:pk>/', views.PlayersView.as_view(), name='player-view'),
    path('team/<int:pk>/', views.PlayersListView.as_view(), name='player-lists'),

##Dashboard urls
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    # path('chart/', views.PieChartView.as_view(), name='chart-data'),

##Match urls
    path('match/view/', views.MatchView.as_view(), name='match_view'),
    path('match/add/', views.MatchAddView.as_view(), name='match-add'),
    path('match/ajax_team_list/', views.AjaxTeamListView.as_view(), name='team-list'),
    path('match/ajax_players_list/', views.AjaxPlayersListView.as_view(), name='player-list'),


##Scorecard urls
    path('score_view/', views.ScoreView.as_view(), name='score_view'),
    path('score_add/', views.ScoreAddView.as_view(), name='score_add'),
    path('score_player_view/', views.ScorePlayerView.as_view(), name='score_player_view'),
    path('team/score/<int:pk>/', views.TeamScoreView.as_view(), name='team-score'),

]

cricket/match/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.db.models import Sum,Count


# Create your models here.

"""
Model class: Base Modal class
Depdency: none
"""
class BaseModal(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    is_delete = models.BooleanField(default=False)

    class Meta:
        db_table = "BaseModal"

"""
Model class: Country class
Depdency: Base model
"""
class Country(models.Model):
    code = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=80, blank=False, unique=True)
    flag = models.ImageField(upload_to='country_flag/', blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "country"

"""
Model class: Team class
Depdency: Base model
"""
class Team(models.Model):
    name = models.CharField(max_length=80, unique=True)
    logo_uri = models.ImageField(upload_to='team_logo/', blank=False)
    club_state = models.CharField(max_length=80, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "team"

    @property
    def total_runs(self):
        runs_obj = ScoreCard.objects.filter(team=self.id)
        return runs_obj.aggregate(Sum('runs'))['runs__sum'] if runs_obj.exists() else 0
        # return total_runs

    @property
    def total_wickets(self):
        wickets_obj = ScoreCard.objects.filter(team=self.id)
        return wickets_obj.aggregate(Sum('wicket'))['wicket__sum'] if wickets_obj.exists() else 0

    @property
    def total_overs(self):
        overs_obj = ScoreCard.objects.filter(team=self.id)
        return overs_obj.aggregate(Sum('over'))['over__sum'] if overs_obj.exists() else 0

    @property
    def total_point(self):
        point_obj = ScoreCard.objects.filter(team=self.id)
        return point_obj.aggregate(Sum('point'))['point__sum'] if point_obj.exists() else 0

    @property
    def total_status(self):
        status_obj = ScoreCard.objects.filter(team=self.id)
        total_status = {}
        win=0; loss=0 ; draw=0
        for status in status_obj:
            if status.status == 'won':
                win=+1
            elif status.status == 'loss':
                loss=+1
            elif status.status == 'draw':
                draw=+1
            else:
                pass
        total_status["win"] = win ; total_status["loss"] = loss ; total_status["draw"] = draw
        return total_status

"""
Model class: User/Player abstracted class
Depdency: Base model, Country model
"""
class User(AbstractUser):

    USER_TYPE_CHOICE = (
        ('admin', 'Admin'),
        ('player', 'Player'),
    )

    PLAYER_TYPE_CHOICE = (
        ('batsman', 'Batsman'),
        ('bowler', 'Bowler'),
        ('wicket keeper', 'Wicket Keeper'),
        ('captain', 'Captain'),
        ('All rounder', 'All Rounder'),
    )

    email = models.EmailField(unique = True)
    image_uri = models.ImageField(upload_to='image_user/', blank=False)
    user_type = models.CharField(max_length=15, choices = USER_TYPE_CHOICE, default="player", blank=False)
    jersy_number = models.CharField(max_length=5, blank=False)
    country = models.ForeignKey(Country, null=True, blank=True, on_delete=models.CASCADE)
    team = models.ForeignKey(Team,related_name="player", null=True, blank=True, on_delete=models.CASCADE)
    player_type = models.CharField(max_length=20, choices = PLAYER_TYPE_CHOICE, default="all rounder", blank=False)
    random_string = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.email

    class Meta:
        db_table = "user"

    def playertype(self):
        return str(self.first_name)+" "+str(self.last_name)+" - "+str(self.player_type)

    @property
    def total_runs(self):
        runs_obj = ScoreCardPlayer.objects.filter(player_id=self.id)
        return runs_obj.aggregate(Sum('runs'))['runs__sum'] if runs_obj.exists() else 0

    @property
    def total_wickets(self):
        wickets_obj = ScoreCardPlayer.objects.filter(player_id=self.id)
        return wickets_obj.aggregate(Sum('wicket'))['wicket__sum'] if wickets_obj.exists() else 0

    @property
    def total_overs(self):
        overs_obj = ScoreCardPlayer.objects.filter(player_id=self.id)
        return overs_obj.aggregate(Sum('over'))['over__sum'] if overs_obj.exists() else 0

    @property
    def total_meadan_overs(self):
        meadan_overs_obj = ScoreCardPlayer.objects.filter(player_id=self.id)
        return meadan_overs_obj.aggregate(Sum('meadan_over'))['meadan_over__sum'] if meadan_overs_obj.exists() else 0

    @property
    def total_fours(self):
        fours_obj = ScoreCardPlayer.objects.filter(player_id=self.id)
        return fours_obj.aggregate(Sum('fours'))['fours__sum'] if fours_obj.exists() else 0

    @property
    def total_sixs(self):
        sixs_obj = ScoreCardPlayer.objects.filter(player_id=self.id)
        return sixs_obj.aggregate(Sum('sixs'))['sixs__sum'] if sixs_obj.exists() else 0

    @property
    def total_fifty(self):
        return ScoreCardPlayer.objects.filter(player_id=self.id).aggregate(Sum('fifty'))['fifty__sum']

    @property
    def total_hundred(self):
        return ScoreCardPlayer.objects.filter(player_id=self.id).aggregate(Sum('hundred'))['hundred__sum']

    @property
    def total_man_of_match(self):
        return ScoreCardPlayer.objects.filter(player_id=self.id,man_of_match=True).count


"""
Model class: Match details class
Depdency: Base model, Team model
"""
class DeviceDetail(BaseModal):
    PLATFORM_CHOICE = (
        ('android', 'android'),
        ('ios', 'ios'),
        ('unknown', 'unknown')
    )
    user = models.ForeignKey(User, related_name= "user_device_detail", on_delete= models.CASCADE)
    platform = models.CharField(max_length= 30, choices= PLATFORM_CHOICE, default= "unknown")
    device_id = models.CharField(max_length= 200, null= False, blank= False, unique= True)
    device_token = models.TextField(null= True, blank= True)
    app_version = models.CharField(max_length= 100, null= True, blank= True)
    access_token = models.TextField(null= True, blank= True)
    refresh_token = models.TextField(null= True, blank= True)

    def __str__(self):
        return self.platform

    def is_ios(self):
        return True if self.platform in ["ios"] else False

    def is_android(self):
        return True if self.platform in ["android"] else False

    class Meta:
        db_table = "device_detail"



"""
Model class: Match details class
Depdency: Base model, Team model
"""
class Match(models.Model):
    name = models.CharField(max_length = 100, blank=False)
    team1 = models.ForeignKey(Team, related_name="team1", blank=False, on_delete=models.CASCADE)
    team2 = models.ForeignKey(Team, related_name="team2", blank=False, on_delete=models.CASCADE)
    match_date = models.DateTimeField(null=True, blank=True)
    match_result = models.CharField(max_length=100, null=True, blank= True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "match"


"""
Model class: Match Player details class
Depdency: Base model, User model, Team modal
"""
class MatchPlayerDetails(BaseModal):
    match_id = models.ForeignKey(Match, related_name="match_player", blank=False, on_delete=models.CASCADE)
    team_id = models.ForeignKey(Team, related_name="match_team", blank=False, on_delete=models.CASCADE)
    player = models.ForeignKey(User, related_name="user_player", blank=False, on_delete=models.CASCADE)

    def __str__(self):
        return self.match_id.name

    class Meta:
        db_table = "match_player_detail"


"""
Model class: ScoreCard class
Depdency: Base model, User model, Team modal
"""
class ScoreCard(BaseModal):
    SCORE_STATUS_CHOICE = (
        ('won', 'Won'),
        ('loss', 'Loss'),
        ('draw', 'Draw'),
    )

    match = models.ForeignKey(Match, related_name="score_card_match", blank=False, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, related_name="score_card_team", blank=False, on_delete=models.CASCADE)
    runs = models.IntegerField(blank=False, default=0)
    wicket = models.IntegerField(blank=False, default=0)
    over = models.FloatField(blank=False, default=0.0)
    status = models.CharField(max_length=10, choices = SCORE_STATUS_CHOICE, blank=True)
    point = models.IntegerField(blank=False, default=0)

    def __str__(self):
        return self.match.name

    class Meta:
        db_table = "score_card"

    def score_status_list(self):
        return self.status


"""
Model class: ScoreCardPlayer class
Depdency: Base model, User model, Team modal
"""
class ScoreCardPlayer(BaseModal):
    PLAYER_STATUS_CHOICE = (
        ('out', 'Out'),
        ('notout', 'Not Out'),
        ('notplayed', 'Not Played'),
    )

    score = models.ForeignKey(ScoreCard, related_name="score_player", blank=False, on_delete=models.CASCADE)
    player_id = models.ForeignKey(User, related_name="player_score", blank=False, on_delete=models.CASCADE)
    runs = models.IntegerField(blank=False, default=0)
    wicket = models.IntegerField(blank=False, default=0)
    over = models.FloatField(blank=False, default=0.0)
    fifty = models.IntegerField(blank=False, default=0)
    hundred = models.IntegerField(blank=False, default=0)
    meadan_over = models.FloatField(blank=False, default=0)
    fours = models.IntegerField(blank=False, default=0)
    sixs = models.IntegerField(blank=False, default=0)
    man_of_match = models.BooleanField(blank=False, default=False)
    status = models.CharField(max_length=10, choices = PLAYER_STATUS_CHOICE, blank=True)

    def __str__(self):
        return self.player_id.first_name

    class Meta:
        db_table = "score_card_player"

cricket/match/templates/match/match_add.html
{% extends "base_site.html" %}
{% block title %} {{ title }} {% endblock title %}
{% block content %}
    <div id="page-wrapper">
        <div class="">
                <ol class="breadcrumb text-right">
                    <li class="breadcrumb-item"><a href="{% url 'match:match_view' %}">Match List</a></li>
                    <li class="breadcrumb-item active ">{{ title }}</li>
                </ol>
            <div class="clearfix"></div>
            <div class="container-fluid">
                <div style="text-align: center;">
                                {% if is_message == 0 %}
                                    <div class="alert alert-danger">
                                    {{message}}
                                    </div>
                                {% else %}

                                {% endif %}

                                </div>
            <div class="row" style="max-width:600px;">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-header">
                            <h2>{{ title }}</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="card-body">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-success alert-dismissable">
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                        </button>
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <br/>
                            <form action="{{ url }}" method="POST"
                                  enctype="multipart/form-data" id="match" data-parsley-validate=""
                                  class="row">

                                {% csrf_token %}
                                <div class="form-group col-md-12">
                                    <label>Match:<span class="error">*</span></label>
                                        <input class="form-control" type="text" name="match"
                                                value ="">
                                </div>

                                <div class="form-group col-md-12">
                                    <label>Team First:<span class="error">*</span></label>
                                               <select name="team1" id="mySelect1" class="form-control">
                                                    <option value=""> Select team </option>
                                                    {% for team in teams %}
                                                            <option value="{{team.id}}">{{team.name}}</option>
                                                    {% endfor %}
                                                </select>
                                </div>

                                  <div class="form-group col-md-12">
                                    <label>Team First Players:<span class="error">*</span></label>
                                               <select name="players1" id="players1" class="form-control" multiple>
                                                    <option value=""> Select players </option>
                                                </select>
                                </div>


                                <div class="form-group col-md-12">
                                    <label>Team Second:<span class="error">*</span></label>
                                               <select id="mySelect2" name="team2" class="form-control">
                                                    <option value=""> Select team </option>
                                                </select>
                                </div>

                                 <div class="form-group col-md-12">
                                    <label>Team Second Players:<span class="error">*</span></label>
                                               <select name="players2" id="players2" class="form-control" multiple>
                                                    <option value=""> Select players </option>
                                                </select>
                                </div>


                                <div class="form-group col-md-12">
                                    <label>Match Date:</label>
                                        <input class="form-control" type="date" name="matchdate"
                                                value ="">
                                </div>
                                <div class="form-group col-md-12">
                                    <label>Match Result:</label>
                                        <input class="form-control" type="text" name="matchresult"
                                                value ="">
                                </div>
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <div class="col-md-12 col-sm-12 col-xs-12 col-md-offset-3">
                                        <a href="{% url 'match:user-lists' %}"
                                           class="btn btn-primary"
                                           role="button">Cancel</a>
                                        <button type="submit" class="btn btn-success">Submit</button>
                                    </div>
                                </div>
                        </div>

                        </form>
                    </div>
                </div>
            </div>
            </div>

        </div>

    </div>
    </div>
{% endblock content %}

cricket/match/templates/match/matchview.html
{% extends "base_site.html" %}
{% block title %} Match View {% endblock title %}
{% block content %}
<div id="page-wrapper">
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">

                    <h3 class="text-themecolor">Match View</h3>


                </div>
                <div class="col-md-7 align-self-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'match:dashboard' %}">Home</a></li>

                        <li class="breadcrumb-item active">Match View</li>

                    </ol>
                </div>
            </div>
            <div class="container-fluid">
                    <div style="text-align: center;">
                                {% if is_message == 1 %}
                                    <div class="alert alert-success">
                                    {{message}}
                                    </div>
                                {% else %}

                                {% endif %}

                                </div>
                <!-- row -->
                <div class="x_panel">
                        <div class="x_title">
                            <h2>Search</h2>
                            <div class="clearfix"></div>
                            <div class="row">
                                <div class="col-sm-6 col-md-4">
                                 <form method="get">
                                     <div class="x_content">
                                         <div class="input-group">
                                             <input type="text" class="form-control" name="search">
                                             <span class="input-group-btn">
                                                 <input class="btn btn-success add-category-btn" type="submit" value="Search">
                                             </span>
                                         </div>
                                     </div>
                                 </form>
                            </div>

                            <div class="col-sm-6 text-right col-md-8">
                                <a href="{% url 'match:match-add' %}" class="btn btn-info"><i  aria-hidden="true"></i> <span>Add Match</span></a>
                            </div>

                            </div>




                        </div>
                    </div>
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <div class="table-wrapper">
                                        <div class="table-responsive text-nowrap">
                                            <table class="table table-striped table-hover table-sm">
                                                <thead>
                                                    <tr>
                                                        <th><b>S.No.</b></th>
                                                        <th><b>Match</b></th>
                                                        <th><b>Team First</b></th>
                                                        <th><b>Team Second</b></th>
                                                        <th><b>Match Date</b></th>
                                                        <th><b>Match Result</b></th>
                                                        <th><b>View</b></th>


                                                    </tr>
                                                </thead>
                                                <tbody>

                                                {% for match in match_list %}
                                                    <tr>
                                                        <td>{{ forloop.counter }}</td>
                                                        <td>{{ match.name }}</td>
                                                        <td>{{ match.team1.name }}</td>
                                                        <td>{{ match.team2.name }}</td>
                                                        <td>{{ match.match_date|date:"Y-m-d" }}</td>
                                                        <td>{{ match.match_result }}</td>
                                                        <td><a href="{% url 'match:score_view' %}">
                                                            <span class="fa fa-eye fa-lg blue"></span></td>
                                                    </tr>
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="row">
                                    <div class="col-md-12">
                                        {% include 'paginator.html' with paginator=match_list %}
                                    </div>
                                    </div>
                                </div>
                                    </div>
                                </div>
                            </div>
                            <!-- ./Basic Table -->
                        </div>
                    </div>
                </div>
            </div>


    {% endblock content %}